-- =============================================================
-- replication_planner--1.0.sql
-- Install script for the Autonomous Replication Planner extension
-- =============================================================

\echo Use "CREATE EXTENSION replication_planner" to load this file. \quit

-- -------------------------------------------------------
-- Schema is created by CREATE EXTENSION (see control file:
-- "schema = replication_planner"). Do not CREATE SCHEMA here.
-- -------------------------------------------------------

-- -------------------------------------------------------
-- Persistent results table (populated by rp_run_full_plan)
-- -------------------------------------------------------
CREATE TABLE replication_planner.plan_results (
    id                  SERIAL PRIMARY KEY,
    run_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    schemaname          NAME        NOT NULL,
    tablename           NAME        NOT NULL,
    final_score         FLOAT8,
    query_freq_score    FLOAT8,
    index_heat_score    FLOAT8,
    table_elig_score    FLOAT8,
    hot_index_cols      TEXT,
    decision            TEXT,       -- REPLICATE_ALL | REPLICATE_FILTERED | SKIP
    row_filter_hint     TEXT,
    skip_reason         TEXT
);

COMMENT ON TABLE replication_planner.plan_results IS
    'Stores the output of the latest rp_run_full_plan() call.';

-- -------------------------------------------------------
-- DDL log table (optional — store generated statements)
-- -------------------------------------------------------
CREATE TABLE replication_planner.generated_ddl (
    id                  SERIAL PRIMARY KEY,
    generated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    publication_name    TEXT,
    tablename           TEXT,
    decision            TEXT,
    row_filter          TEXT,
    ddl_statement       TEXT,
    applied             BOOLEAN NOT NULL DEFAULT false
);

COMMENT ON TABLE replication_planner.generated_ddl IS
    'Stores publication DDL statements generated by rp_generate_publication_ddl().';

-- -------------------------------------------------------
-- Phase 1-A: Index Statistics Collector
-- -------------------------------------------------------
CREATE FUNCTION replication_planner.collect_index_stats()
RETURNS TABLE (
    schemaname        NAME,
    tablename         NAME,
    indexname         NAME,
    idx_scans         BIGINT,
    idx_blks_read     BIGINT,
    idx_blks_hit      BIGINT,
    hit_ratio         FLOAT8,
    table_total_scans BIGINT,
    scan_share        FLOAT8,
    index_columns     TEXT,
    is_unique         BOOLEAN,
    is_primary        BOOLEAN,
    heat_score        FLOAT8,
    recommendation    TEXT
)
AS 'replication_planner', 'rp_collect_index_stats'
LANGUAGE C STRICT;

COMMENT ON FUNCTION replication_planner.collect_index_stats() IS
    'Phase 1-A: Reads pg_stat_user_indexes + pg_statio_user_indexes and '
    'computes per-index heat scores (hit ratio + scan share).';

-- -------------------------------------------------------
-- Phase 1-B: Table Distribution Collector
-- -------------------------------------------------------
CREATE FUNCTION replication_planner.collect_table_stats()
RETURNS TABLE (
    schemaname            NAME,
    tablename             NAME,
    row_estimate          BIGINT,
    total_pages           BIGINT,
    seq_scans             BIGINT,
    idx_scans_total       BIGINT,
    n_dead_tup            BIGINT,
    n_mod_since_analyze   BIGINT,
    write_ratio           FLOAT8,
    has_pk                BOOLEAN,
    column_count          INT,
    eligibility_score     FLOAT8,
    skip_reason           TEXT
)
AS 'replication_planner', 'rp_collect_table_stats'
LANGUAGE C STRICT;

COMMENT ON FUNCTION replication_planner.collect_table_stats() IS
    'Phase 1-B: Reads pg_class + pg_stat_user_tables to compute '
    'table eligibility scores for replication.';

-- -------------------------------------------------------
-- Phase 1-C: Workload Pattern Collector
-- -------------------------------------------------------
CREATE FUNCTION replication_planner.collect_workload_stats()
RETURNS TABLE (
    query_hash      BIGINT,
    calls           BIGINT,
    total_exec_ms   FLOAT8,
    mean_exec_ms    FLOAT8,
    call_share      FLOAT8,
    query_snippet   TEXT,
    contains_where  BOOLEAN,
    heat_tier       TEXT      -- CRITICAL | HOT | WARM | COLD
)
AS 'replication_planner', 'rp_collect_workload_stats'
LANGUAGE C STRICT;

COMMENT ON FUNCTION replication_planner.collect_workload_stats() IS
    'Phase 1-C: Reads pg_stat_statements to identify hot SELECT patterns '
    'and classify each query into a heat tier.';

-- -------------------------------------------------------
-- Phase 2: Heuristic Analysis + Scoring
-- -------------------------------------------------------
CREATE FUNCTION replication_planner.analyze_and_score()
RETURNS TABLE (
    schemaname        NAME,
    tablename         NAME,
    final_score       FLOAT8,
    query_freq_score  FLOAT8,
    index_heat_score  FLOAT8,
    table_elig_score  FLOAT8,
    hot_index_cols    TEXT,
    decision          TEXT,       -- REPLICATE_ALL | REPLICATE_FILTERED | SKIP
    row_filter_hint   TEXT,
    skip_reason       TEXT
)
AS 'replication_planner', 'rp_analyze_and_score'
LANGUAGE C STRICT;

COMMENT ON FUNCTION replication_planner.analyze_and_score() IS
    'Phase 2: Heuristic engine. Combines index heat, query frequency, '
    'and table eligibility into a final score and replication decision.';

-- -------------------------------------------------------
-- Phase 3-A: Publication DDL Generator
-- -------------------------------------------------------
CREATE FUNCTION replication_planner.generate_publication_ddl()
RETURNS TABLE (
    publication_name  TEXT,
    tablename         TEXT,
    decision          TEXT,
    row_filter        TEXT,
    ddl_statement     TEXT
)
AS 'replication_planner', 'rp_generate_publication_ddl'
LANGUAGE C STRICT;

COMMENT ON FUNCTION replication_planner.generate_publication_ddl() IS
    'Phase 3: Generates ready-to-run CREATE PUBLICATION DDL '
    'including row filters for REPLICATE_FILTERED tables (PG15+).';

-- -------------------------------------------------------
-- Phase 3-B: Apply DDL (saves to generated_ddl table)
-- -------------------------------------------------------
CREATE FUNCTION replication_planner.save_publication_ddl()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    v_count INT := 0;
BEGIN
    INSERT INTO replication_planner.generated_ddl
        (publication_name, tablename, decision, row_filter, ddl_statement)
    SELECT publication_name, tablename, decision, row_filter, ddl_statement
    FROM   replication_planner.generate_publication_ddl();

    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN format('Saved %s DDL statements to replication_planner.generated_ddl', v_count);
END;
$$;

-- -------------------------------------------------------
-- Full pipeline runner
-- -------------------------------------------------------
CREATE FUNCTION replication_planner.run_full_plan()
RETURNS TEXT
AS 'replication_planner', 'rp_run_full_plan'
LANGUAGE C STRICT;

COMMENT ON FUNCTION replication_planner.run_full_plan() IS
    'Runs the complete telemetry → analysis → scoring pipeline and '
    'persists results to replication_planner.plan_results.';

-- -------------------------------------------------------
-- Convenience views
-- -------------------------------------------------------

-- Quick overview: tables recommended for replication
CREATE VIEW replication_planner.v_replicate_targets AS
SELECT
    schemaname,
    tablename,
    round(final_score::numeric, 4)      AS score,
    decision,
    hot_index_cols,
    row_filter_hint
FROM replication_planner.plan_results
WHERE decision IN ('REPLICATE_ALL', 'REPLICATE_FILTERED')
ORDER BY final_score DESC;

COMMENT ON VIEW replication_planner.v_replicate_targets IS
    'Tables the planner recommends replicating, ordered by score.';

-- Index heat leaderboard
CREATE VIEW replication_planner.v_index_heat AS
SELECT
    schemaname,
    tablename,
    indexname,
    idx_scans,
    round(hit_ratio::numeric, 4)        AS hit_ratio,
    round(scan_share::numeric, 4)       AS scan_share,
    round(heat_score::numeric, 4)       AS heat_score,
    recommendation,
    index_columns
FROM replication_planner.collect_index_stats()
ORDER BY heat_score DESC;

COMMENT ON VIEW replication_planner.v_index_heat IS
    'Index heat leaderboard. Use to identify dominant read indexes.';

-- Workload top-10
CREATE VIEW replication_planner.v_hot_queries AS
SELECT
    heat_tier,
    calls,
    round(call_share::numeric * 100, 2) AS call_pct,
    round(mean_exec_ms::numeric, 2)     AS mean_ms,
    contains_where,
    query_snippet
FROM replication_planner.collect_workload_stats()
WHERE heat_tier IN ('CRITICAL', 'HOT')
ORDER BY calls DESC
LIMIT 50;

COMMENT ON VIEW replication_planner.v_hot_queries IS
    'Top-50 hottest SELECT queries from pg_stat_statements.';

-- Histogram distribution for a given table/column
-- (pure SQL, uses pg_stats)
CREATE VIEW replication_planner.v_column_histograms AS
SELECT
    schemaname,
    tablename,
    attname                             AS column_name,
    n_distinct,
    correlation,
    most_common_vals::text              AS top_values,
    most_common_freqs::text             AS top_freqs,
    histogram_bounds::text              AS histogram_bounds,
    null_frac
FROM pg_stats
WHERE schemaname NOT IN ('pg_catalog','information_schema')
ORDER BY schemaname, tablename, attname;

COMMENT ON VIEW replication_planner.v_column_histograms IS
    'Exposes pg_stats histogram and MCV data for all user table columns.';

-- -------------------------------------------------------
-- GUC documentation view
-- -------------------------------------------------------
CREATE VIEW replication_planner.v_settings AS
SELECT name, setting, unit, short_desc
FROM pg_settings
WHERE name LIKE 'replication_planner.%'
ORDER BY name;

COMMENT ON VIEW replication_planner.v_settings IS
    'Shows current replication_planner GUC parameter values.';
